# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SearchBarExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SearchBar', git: 'https://github.com/aashishtamsya/SearchBar', branch: 'feature/5'

  # Pods for SearchBarExample

end
